language: node_js
node_js:
  - 14
script:
  - prettier --check "src/**/*.(ts|tsx)"
  - eslint 'src/**'
  - npm run test:coveralls
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: fordevs-reactclean
  skip_cleanup: true
