version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1.29.0

jobs:
  install_node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:coveralls
          name: Run tests coverages

  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/dist
          paths: .

  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/dist
      - heroku/deploy-via-git:
          force: true

workflows:
  deploy:
    jobs:
      - install_node
      - test
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          start: yarn dev:base
          wait-on: 'http://localhost:8080'
      - build
      - deploy:
          requires:
            - install_node
            - test
            - cypress_install
            - cypress_run
            - build
          filters:
            branches:
              only: master
