version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1.29.0

jobs:
  install_node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

  test_and_build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          name: Install cypress dependecies
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:coveralls
          name: Run tests coverages
      - run:
          command: npx cypress install
          name: Install cypress
      - run:
          command: yarn test:cypress:ci
          name: Run tests cypress
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/dist
          paths: .

  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/dist
      - heroku/deploy-via-git:
          force: true

workflows:
  deploy:
    jobs:
      - install_node
      - test_and_build
      - deploy:
          requires:
            - install_node
            - test_and_build
          filters:
            branches:
              only: master
