version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:coveralls
          name: Run tests coveralls
      - run:
          command: yarn test:cypress:ci
          name: Run cypress tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/dist
          paths: .
  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/dist
      - heroku/deploy-via-git:
          force: true

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
